title: Biodiesel Equipment Website
email: order@biodiesel.equipment
description: >
  CBR Beyond Technologies website is dedicated to providing 
  equipment and services with regards to Biodiesel production
  in the Philippines.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://biodiesel.equipment" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - .vscode/
   - docs/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
