title: CBR Beyond Technologies Enterprises
email: order@biodiesel.equipment
description: >
  High Quality, Easy to Use Biodisel Equipment, 
  Products & Services in the Philippines
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://biodiesel.equipment" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  biodiesel.equipment

# SEO
logo: /images/logo.full.jpg
social:
  name: biodiesel.equipment
  links:
    - https://github.com/biodiesel.equipment

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - .vscode/
   - docs/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
